### ISSUE TITLE
ASCDB needs a tagline

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/MQCAS#5]
**Data Location**
ReactionDataset ASCDB

**Describe the issue**
Its tagline is None.

**Comment by dgasmith** [comment]
@PierMorgante For example S22's tagline is something like "22 small intermolecular biocomplexes" or the like.

**Comment by PierMorgante** [comment]
Hi Daniel and Matt, is "A small database of statistically significant chemical properties ranging from transition metals to artificial molecules" okay or is it too long?

**Comment by dgasmith** [comment]
Can you add a `...curated from x.` where `x` could be `literature datasets` or similar.

**Comment by PierMorgante** [comment]
What about "A small database of statistically significant chemical properties ranging from transition metals to artificial molecules coming from the three largest computational databases in the literature: MGCDB84, GMTKN55, and Minnesota 2015B"?

**Comment by dgasmith** [comment]
Sounds good, can you make a PR to update this? Probably a `ds = ...; ds.data.tagline = ...; ds.save()`.

**Comment by mattwelborn** [comment]
To get you started:

```
import qcportal as ptl

client = ptl.FractalClient.from_file()

ds = client.get_collection("ReactionDataset", "ASCDB")
ds.data.__dict__["tagline"] = "TODO"
ds.save()
```
